#
# Site Info
#
# If you want specific meta info for your <head></head> tags
#
title: TrentaFit - 30 Day at Home Fitness Challenge
author: TrentaFit
email: your-email@domain.com
description: Stepping Stone Nutrition offers Nutrition, Wellness, and Lactation Counseling and Services in Southeast Wisconsin.
url: www.TrentaFit.com
logo: /images/app-icon.png

#
# !! You don't need to change any of the configuration flags below !!
#
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed

# Exclude these files from your production _site
exclude:
  - README.md